# Generated by Django 3.2.3 on 2021-06-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_alter_photo_file'),
        ('users', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='room',
            field=models.ManyToManyField(to='rooms.Room'),
        ),
    ]
